### ISSUE TITLE
Kompozicija rotacija oko razlicitih osa

### ISSUE THREAD

**Issue by milana-kovacevic** [MATF-RG16/RG16-013-rubik#1]
:bug: Kada rotiram delove kocke prvo oko jedne pa oko druge ose dobijam ovako kul 'kocku':
Da li je to mozda do redosleda kojim mnozis matrice?

![rubik bug](https://cloud.githubusercontent.com/assets/23002077/20867200/0dddc202-ba3f-11e6-87be-dabb4fe78620.gif)

**Comment by IvanRistovic** [comment]
Moja nocna mora... Hvala sto si me podsetila na nju.

To i dalje razmisljam kako da resim, zbog toga sam i napravio update funkciju, ona bi trebalo da promeni pozicije matrica nakon svake rotacije. I dalje je u eksperimentalnoj fazi, radilo je za rotacije oko Z ose ali za Y imam nekih problema, zato sam je iskomentarisao dok ne shvatim u cemu je problem.

Svakako kad uradim, dobijas obavestenje :pager:

**Comment by milana-kovacevic** [comment]
Zasto u update funkciji u matrices.c (deo koji je komantarisan) dodeljujes konstantne vrednosti??? I zasto niko ovo nije primetio do sad :open_mouth: 
Kada rotiras kocku to vise nece biti te vrednosti, vec vrednosti na tim lokacijama u nizu. Mislim da ti zato ne radi...

**Comment by IvanRistovic** [comment]
Pa to je samo ideja, zato je i pod komentarima :wink: Da, u pravu si, treba da se dodeljuju vrednosti na lokacijama. Ali onda ce mi biti potreban novi niz. Takodje sam mislio da uklonim view_matrix skroz, jer mislim da je ona potencijalni problem takodje, jer se rotacije primenjuju u koord. sistemu nastalom od primene te matrice na modelview matricu. Ali svakako, to sto si predlozila mora da radi. Cak sam i testirao pre par dana na Z slojevima, i radilo je ali samo zato sto sam menjao razlicite delove tog niza :wink: Samo ima dosta bagova i nije jos spremno skroz. Doradicu svakako u narednih par dana, hvala!

**Comment by IvanRistovic** [comment]
![1](https://cloud.githubusercontent.com/assets/19779112/21112108/bfb22e08-c0a4-11e6-95e4-cd1f0621798e.gif)

Deeeelimicno popravljeno, iz nekog razloga mi Y negativne i dalje pomeraju pogresne delove kocke, i to moram da skontam zasto.

**Comment by milana-kovacevic** [comment]
Hahah, ovaj gif savrseno opisuje tvoje probleme :laughing: 
Mozes li da postavis i gif tog drugog preostalog baga? Bas me zanima :wink:

**Comment by IvanRistovic** [comment]
Evo samo za tebe:

![1](https://cloud.githubusercontent.com/assets/19779112/21119718/227c5c88-c0c4-11e6-892a-cfa2719b0c73.gif)

Sve radi osim Y negativne :sob:

**Comment by ivan-cukic-matf** [comment]
Uobičajen pristup nije da se pamte rotacije, ni sve kockice odvojeno. Pamte se samo podaci o trenutnim bojama 9x9 za svaku od strana (interni model podataka). Zamislite da je svako polje piksel na ekranu - kad želimo da nacrtamo da se nešto pomerilo - ugasimo jedan piksel i ukljucimo drugi.

To bi bila logika programa koja je potpuno nezavisna od prikaza - a prikazi postoje raznorazni [1].

Onda je na pogledu samo da implementira tranziciju izmedju dva stanja modela - ovde bi bila prikazana kao rotacija odredjenog bloka kocke. Umesto da postoji kompozicija rotacija, imali biste jednu jedinu rotaciju, i to samo tokom animacije od 0 do pi/2 - kad dostigne pi/2, resetujete kocku i prikažete nove podatke na njoj.

Ali je ovako zanimljivije. :)

[1] https://www.google.com/search?q=rubiks+cube+program&source=lnms&tbm=isch

**Comment by IvanRistovic** [comment]
Zanimljiv pristup, mada je to po meni ogroman cheat :smile:  Meni je ova moja implementacija prva stvar koja mi je pala na pamet, i cini mi se intuitivnijom i svakako laksom za kodiranje. Jedina mana mog pristupa je to sto je mozda malo sporija zbog svog tog mnozenja matrica...

**Comment by ivan-cukic-matf** [comment]
Množenje matrica nije toliki problem - glavni problem je to što otvarate sebi prostor da pravite greške.

Slažem se da je ovo što ste uradili najlogičniji izbor, i dobro je što ste tako radili - više ste ovako naučili o transformacijama u OpenGL-u nego što biste onako.

Onaj pristup, i pored toga što je *cheat*, je nešto što ćete u većini programa morati da radite - da razdvajate model od pogleda.

**Comment by IvanRistovic** [comment]
Ideja je i bila da iskoristim ovaj mali projekat kako bih istrazio malo OpenGL, zato i dodajem neke nebitne stvari poput npr. pozadinskih tekstura, sto sa strane korisnika moze izgledati potpuno nebitno, ali sa moje strane je vezba OpenGL-a generalno.

Mozda izgleda kao da sam protiv tog generalnog pristupa, ali zapravo bih u buducnosti uvek to izabrao, a ne ovakva resenja kao sada.

**Comment by IvanRistovic** [comment]
Milana, ovaj bug vise ne postoji! :construction_worker_man: 

:fire: :fire: :fire: 
:fire: :bug: :fire: 
:fire: :fire: :fire:
