### ISSUE TITLE
Dokumentacija koda

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-013-rubik#2]
Kod jeste većinom razumljiv, ali ipak treba dokumentovati detaljnije šta koji deo radi

**Comment by IvanRistovic** [comment]
Svakako. Dosta delova koda je jos u "eksperimentalnoj" fazi. Onog trenutka kada mi svi testovi prodju, obavezno cu ga pravilno dokumentovati.
