### ISSUE TITLE
Snimak ekrana

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-013-rubik#3]
Napravite snimak ekrana od 30-ak sekundi za demonstraciju igre. Neka bude 800x600 rezolucija, format zapisa mpg.

**Comment by IvanRistovic** [comment]
https://www.youtube.com/watch?v=XGPYZhePjKo

Linkovi za download:
1280x760: https://drive.google.com/open?id=0B9tXL_bzLWBLSmxHVzBncjRJWDQ
800x600: https://drive.google.com/open?id=0B9tXL_bzLWBLeG81QjdDQy12eU0

**Comment by IvanRistovic** [comment]
https://www.youtube.com/watch?v=XGPYZhePjKo

Linkovi za download:
1280x760: https://drive.google.com/open?id=0B9tXL_bzLWBLSmxHVzBncjRJWDQ
800x600: https://drive.google.com/open?id=0B9tXL_bzLWBLeG81QjdDQy12eU0
